export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_RECIPES_PENDING = 'REQUEST_RECIPES_PENDING';
export const REQUEST_RECIPES_SUCCESS = 'REQUEST_RECIPES_SUCCESS';
export const REQUEST_RECIPES_FAILED = 'REQUEST_RECIPES_FAILED';

export const REQUEST_BY_ID_RECIPES_PENDING = 'REQUEST_RECIPES_PENDING';
export const REQUEST_BY_ID_RECIPES_SUCCESS = 'REQUEST_RECIPES_SUCCESS';
export const REQUEST_BY_ID_RECIPES_FAILED = 'REQUEST_RECIPES_FAILED';