module.exports = {
    CHANGE_SEARCH_FIELD: 'CHANGE_SEARCH_FIELD',

    REQUEST_RECIPES_PENDING: 'REQUEST_RECIPES_PENDING',
    REQUEST_RECIPES_SUCCESS: 'REQUEST_RECIPES_SUCCESS',
    REQUEST_RECIPES_FAILED: 'REQUEST_RECIPES_FAILED',

    REQUEST_BY_ID_RECIPES_PENDING: 'REQUEST_BY_ID_RECIPES_PENDING',
    REQUEST_BY_ID_RECIPES_SUCCESS: 'REQUEST_BY_ID_RECIPES_SUCCESS',
    REQUEST_BY_ID_RECIPES_FAILED: 'REQUEST_BY_ID_RECIPES_FAILED',

    ADD_RECIPES_PENDING: 'ADD_RECIPES_PENDING',
    ADD_RECIPES_SUCCESS: 'ADD_RECIPES_SUCCESS',
    ADD_RECIPES_FAILED: 'ADD_RECIPES_FAILED',

    ADD_USER_PENDING: 'ADD_USER_PENDING',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILED: 'ADD_USER_FAILED',

    LIKE_RECIPE_PENDING: 'LIKE_RECIPE_PENDING',
    LIKE_RECIPE_SUCCESS: 'LIKE_RECIPE_SUCCESS',
    LIKE_RECIPE_FAILED: 'LIKE_RECIPE_FAILED',

    UNLIKE_RECIPE_PENDING: 'UNLIKE_RECIPE_PENDING',
    UNLIKE_RECIPE_SUCCESS: 'UNLIKE_RECIPE_SUCCESS',
    UNLIKE_RECIPE_FAILED: 'UNLIKE_RECIPE_FAILED',

    REQUEST_SAVED_RECIPES_PENDING: 'REQUEST_SAVED_RECIPES_PENDING',
    REQUEST_SAVED_RECIPES_SUCCESS: 'REQUEST_SAVED_RECIPES_SUCCESS',
    REQUEST_SAVED_RECIPES_FAILED: 'REQUEST_SAVED_RECIPES_FAILED',

    REQUEST_FAVORITE_RECIPES_PENDING: 'REQUEST_FAVORITE_RECIPES_PENDING',
    REQUEST_FAVORITE_RECIPES_SUCCESS: 'REQUEST_FAVORITE_RECIPES_SUCCESS',
    REQUEST_FAVORITE_RECIPES_FAILED: 'REQUEST_FAVORITE_RECIPES_FAILED',

    FAVORITES_RECIPES_NUMBER: 3,
    RECIPES_COLLECTION: "recipes",
    USERS_COLLECTION: "users",
    SAVED_COLLECTION: "savedRecipes"
}